services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/sweech_thread_flow_db
      - JWT_SECRET=abcdef1234567890abcdef1234567890abcdef1234567890abcdef1234567890
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run start:dev

  db:
    image: postgres:14.2
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sweech_thread_flow_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: